### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kenanmasri** [bradmontgomery/django-rainbowtests#10]
Please release a new version, compatible with Django 4.0.
Thanks for the awesome package!
Edit: sorry I thought it doesn't works already

**Comment by bradmontgomery** [comment]
Hi @kenanmasri, Thanks for the update. Can you confirm what version of python you're using and the precise version of Django?

☝️ That'd let me update the Readme and at least let folks know this still works. Thanks! 😄

**Comment by kenanmasri** [comment]
The fact is that I'm using Django 3.2 for now. When I tried to use 4 I thought this package was not allowing me to do so.

Anyway I tested with Python 3.9.7 and Django 4.0 it works.

Thanks
