### ISSUE TITLE
Push new release

### ISSUE THREAD

**Issue by thijstriemstra** [bradmontgomery/django-rainbowtests#4]
Can you release a new version? I'd like to try it out but there's some commits regarding python3 that are not included in the latest release (0.2.1 from 2014-07-19).

**Comment by bradmontgomery** [comment]
The version on pypi (0.2.1) should be python-3 compatible. I'm using it on python 3.4. The 2 commits after that tag were only for documentation changes, so I'm a little hesitant to push out a release that doesn't really do anything.

**Comment by thijstriemstra** [comment]
Oh my mistake, thanks for the feedback.

**Comment by bradmontgomery** [comment]
No problem! Feel free to open an issue if you have any problems or any new ideas. Thanks for checking it out!
